'use client';

import { ReactNode } from 'react';
import './globals.css'; // Tailwind import
import Navbar from './components/NavBar';
import Footer from './components/Footer'; // <-- Add this import

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Gaegu:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-white text-white overflow-x-hidden font-gaegu">
        <Navbar />
        <main className="pt-14 min-h-screen">{children}</main>
        <Footer /> {/* <-- Add this line for the footer */}
      </body>
    </html>
  );
}


// uncomment this if u want white background for carousel
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
